title: "jihak's blog"
title_seperator: "|"
email: jooin2000@naver.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: jihak
paginate: 6
disqus: 'hakblog'
locale: ko_KR
lang: ko_KR
feed_items: 6
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rough
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-NXJZHHVXPE

# Authors
authors:
  jiahk:
    name: jihak
    display_name: jihak
    avatar: 'assets/images/sal.png'
    email: jooin2000@naver.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/
    description: "HI~"

# Social
social:
  instagram: https://www.instagram.com/easy_hak2/
  facebook: https://www.facebook.com/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives