title: "jihak's blog"
email: jooin2000@naver.com
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: jihak
paginate: 30
disqus: 'blog'
comments: false
locale: ko
lang: ko
feed_items: 6
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  jiahk:
    name: jihak
    display_name: jihak
    avatar: 'assets/images/sal.png'
    email: jooin2000@naver.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/
    description: ""

# Social
social:
  instagram: https://www.instagram.com/easy_hak2/
  facebook: https://www.facebook.com/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
